version: '3.8'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=analytics
      - ALLOW_EMPTY_PASSWORD=yes
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DB=analytics
    depends_on:
      - clickhouse
    # volumes:
      # - ./server:/app
      # - /app/node_modules

volumes:
  clickhouse-data:
